version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER:  angular
      POSTGRES_PASSWORD:  Sys@dmin1
      POSTGRES_DB:  angular_training
    ports:
      - 5432:5432

#  angular-training:
#    restart: always
#    image: angular-training
#    build:
#      dockerfile: Dockerfile
#      context: .
#    environment:
#      - TZ=Asia/Bangkok
#    ports:
#      - 8081:8081
#    networks:
#      - network-angular-training
#networks:
#  network-angular-training:
#    driver: bridge
